CREATE TABLE Materias (
idMateria INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(30),
carrera VARCHAR(30),
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
STATUS BOOL DEFAULT true
);

CREATE TABLE Alumnos (
idAlumno INT PRIMARY KEY AUTO_INCREMENT,
numControl VARCHAR(8) NOT NULL,
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
sexo ENUM('F','M') NOT NULL,
semestre TINYINT NOT NULL,
carrera VARCHAR(50) NOT NULL,
especialidad VARCHAR(30),
fechaNacimiento DATE NOT NULL,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
STATUS BOOL DEFAULT true
)